<?php
/*
Plugin Name: Ajax test
URI: https://www.smashingmagazine.com/2011/10/how-to-use-ajax-in-wordpress/#adding-javascript-to-the-mix

*/

//de layout van de pagina ajaxtest staat onvermijdelijk in het thema divicchild*/

function my_user_vote() {

   if ( !wp_verify_nonce( $_REQUEST['nonce'], "my_user_vote_nonce")) {
      exit("No naughty business please");
   }   

   $vote_count = get_post_meta($_REQUEST["post_id"], "votes", true);
   $vote_count = ($vote_count == '') ? 0 : $vote_count;
   $new_vote_count = $vote_count + 1;

   $vote = update_post_meta($_REQUEST["post_id"], "votes", $new_vote_count);

   if($vote === false) {
      $result['type'] = "error";
      $result['vote_count'] = $vote_count;
   }
   else {
      $result['type'] = "success";
      $result['vote_count'] = $new_vote_count;
   }

   if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
      $result = json_encode($result);
      echo $result;
   }
   else {
      header("Location: ".$_SERVER["HTTP_REFERER"]);
   }

   die();

}

function my_must_login() {
   echo "You must log in to vote"; 
   die();
}
add_action("wp_ajax_my_user_vote", "my_user_vote");
add_action("wp_ajax_nopriv_my_user_vote", "my_must_login");
//the 2 hooks are generated by admin-ajax.php


function my_script_enqueuer() {
   wp_register_script( "my_voter_script", plugins_url('/ajaxtest/my_voter_script.js','_FILE_'), array('jquery'));
   wp_localize_script( 'my_voter_script', 'myAjax', array( 'ajaxurl' => admin_url( 'admin-ajax.php' )));        
	//Localizes a registered script with data for a JavaScript variable.

   wp_enqueue_script( 'jquery' );
   wp_enqueue_script( 'my_voter_script' );

}
add_action( 'init', 'my_script_enqueuer' );
//zonder deze javascript file kunnen de votes ook geupdatet worden, doch dit gaat gepaard met paginaspringen 















?>
